#! /usr/bin/env bash

declare -a SCRIPTS=(
repos
gcs
)

function symlink_scripts {
  echo 'installing scripts...'
  for script in ${SCRIPTS[@]}; do
    echo " - ${script}"
    ln -sf "${PWD}/${script}" "/usr/local/bin/${script}"
  done
}

function install {
  symlink_scripts
}

install
echo "Finished."
